
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/qmusic_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: dev
    password: dev
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zizi.qmusic.server.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      zizi:
        qmusic:
          server: debug # 本项目debug 打印sql日志
    java:
      sql: debug
    org:
      mybatis:
        spring: debug
      springframework:
        web: debug
  file: /logs/Qmusic-server.log


---
spring:
  profiles: dev
server:
  port: 8221
---
spring:
  profiles: test
server:
  port: 8222
---
spring:
  profiles: prd
server:
  port: 8223
---

