
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:db/schema.sql
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true

logging:
  level:
    org:
      springframework:
        web: debug
  file: D:/logs/Qmusic-server.log


---
spring:
  profiles: dev
server:
  port: 8221
---
spring:
  profiles: test
server:
  port: 8222
---
spring:
  profiles: prd
server:
  port: 8223
---