create database qmusic_dev;
USE qmusic_dev;
/**
 * 用户表
 */
DROP TABLE IF EXISTS q_user;
CREATE TABLE q_user
(
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  ip VARCHAR(16) NULL DEFAULT NULL COMMENT '源ip',
  email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱'
)ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;